In [2]:
import pandas as pd
import numpy as np
import scipy as sp
a={"Y-actual":[20,30,40,50,60],
   "Y-pred":[20.5,30.3,40.2,50.6,60.7]}
df=pd.DataFrame(a)
df


Y-actual  Y-pred
0        20    20.5
1        30    30.3
2        40    40.2
3        50    50.6
4        60    60.7

In [16]:
yp=df['Y-pred']
print(yp)

0    20.5
1    30.3
2    40.2
3    50.6
4    60.7
Name: Y-pred, dtype: float64


In [15]:
y=df['Y-actual']
print(y)

0    20
1    30
2    40
3    50
4    60
Name: Y-actual, dtype: int64


In [41]:
error=(y-yp)**2
print(error)


0    0.25
1    0.09
2    0.04
3    0.36
4    0.49
dtype: float64


In [54]:
import numpy as np

mean=np.mean(error)
mae=np.mean(abs(y-yp))
rsme=np.sqrt(mean)

print("root_mean_square_error",rsme)
print("mean_absolute_error",mae)
print("mean_square_error",mean)

root_mean_square_error 0.49598387070549127
mean_absolute_error 0.4600000000000016
mean_square_error 0.24600000000000147


In [56]:
import numpy as np
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix as cm_sklearn
def calculate_metrics(y_actual, y_pred, num_classes):
    cm = np.zeros((num_classes, num_classes), dtype=int)
    for true, pred in zip(y_actual, y_pred):
        cm[true, pred] += 1
    acc = accuracy_score(y_actual, y_pred)
    print(f"Accuracy: {acc}")
    for class_label in range(num_classes):
        tp, fp, fn = cm[class_label, class_label], cm[:, class_label].sum() - cm[class_label, class_label], cm[class_label, :].sum() - cm[class_label, class_label]
        precision = tp / (tp + fp) if tp + fp > 0 else 0
        recall = tp / (tp + fn) if tp + fn > 0 else 0
        f1 = 2 * (precision * recall) / (precision + recall) if precision + recall > 0 else 0
        print(f"Class {class_label}: Precision: {precision}, Recall: {recall}, F1 Score: {f1}")
    print("\nConfusion Matrix:")
    print(cm)


y_actual = [0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2]
y_pred = [0, 0, 1, 2, 2, 1, 0, 2, 0, 2, 0, 0, 1, 2, 2]


num_classes = 3
calculate_metrics(y_actual, y_pred, num_classes)
print("\nUsing scikit-learn:")
print(f"Accuracy: {accuracy_score(y_actual, y_pred)}")
print(f"Precision (per class): {precision_score(y_actual, y_pred, average=None, labels=[0, 1, 2])}")
print(f"Recall (per class): {recall_score(y_actual, y_pred, average=None, labels=[0, 1, 2])}")
print(f"F1 Score (per class): {f1_score(y_actual, y_pred, average=None, labels=[0, 1, 2])}")
print(f"Confusion Matrix:\n{cm_sklearn(y_actual, y_pred)}")


Accuracy: 0.3333333333333333
Class 0: Precision: 0.3333333333333333, Recall: 0.4, F1 Score: 0.3636363636363636
Class 1: Precision: 0.3333333333333333, Recall: 0.2, F1 Score: 0.25
Class 2: Precision: 0.3333333333333333, Recall: 0.4, F1 Score: 0.3636363636363636

Confusion Matrix:
[[2 1 2]
 [2 1 2]
 [2 1 2]]

Using scikit-learn:
Accuracy: 0.3333333333333333
Precision (per class): [0.33333333 0.33333333 0.33333333]
Recall (per class): [0.4 0.2 0.4]
F1 Score (per class): [0.36363636 0.25       0.36363636]
Confusion Matrix:
[[2 1 2]
 [2 1 2]
 [2 1 2]]
